version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "ea:5e:5f:1c:fb:e0:7c:6d:d8:ad:25:bd:75:40:9f:95"
      - run: bash .circleci/deploy.bash
    branches:
      only:
        - master
      ignore: gh-pages
